name: CI

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build
        run: nix build -L

      - uses: actions/upload-artifact@v5
        with:
          name: website
          path: result

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build Static
        run: nix build -L .#website-static

      - uses: actions/upload-artifact@v5
        with:
          name: website-static
          path: result

      - name: Patch
        run: |
          mv result result-old
          mkdir result
          cp -r result-old/* result
          chmod +w -R result
          echo "User-agent: *\nDisallow: /" > result/browser/robots.txt

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2a09613716e511a8fe8ca74abc084762
          command: pages deploy result/browser --project-name=dd-ix
          gitHubToken: ${{ github.token }}
          packageManager: npm
