name: CI

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Check
        run: nix flake check -L

      - name: Build
        run: nix build -L

